spring:
  application:
    name: gateway

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true