eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 3001
spring:
  application:
    name: eureka_consumer_feign

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
