eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  instance:
    lease-renewal-interval-in-seconds : 5
    lease-expiration-duration-in-seconds : 5
server:
  port: 2001
spring:
  application:
    name: eureka-client
