eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 3002
spring:
  application:
    name: eureka-consumer-feign

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
